# Generated by Django 4.1.7 on 2023-03-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Marz", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="name1",
        ),
        migrations.AddField(
            model_name="product",
            name="name2",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
